"""
Encrypted local secret storage for nsclient_test_base.

Architecture:
  Key  : ~/.nsclient_test/.secret_key   (outside the repo — never in git)
  Store: data/secrets.json              (gitignored — encrypted Fernet ciphertext)

The key never touches the repo directory. Even if data/secrets.json were accidentally
committed, it cannot be decrypted without the key file.

First use: the key is auto-generated by store_secret().  Run
  python tool/manage_secrets.py init
to generate it explicitly before storing anything.

Usage:
    from util_secrets import store_secret, get_secret, list_secrets, delete_secret

    store_secret("confluence_api_token", "ATATT3xFfGF0...")
    token = get_secret("confluence_api_token")   # → plaintext str
    names = list_secrets()                       # → ["confluence_api_token", ...]
    delete_secret("confluence_api_token")
"""

import json
import logging
import time
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

# ── Well-known secret names ───────────────────────────────────────────────────
# Use these constants instead of raw strings to avoid typos.

SECRET_CONFLUENCE_API_TOKEN    = "confluence_api_token"
SECRET_INSTALL_TOKEN           = "install_token"           # msiexec token=
SECRET_ORG_KEY                 = "org_key"                 # Linux .run -o
SECRET_ENROLL_AUTH_TOKEN       = "enroll_auth_token"       # IDP enrollauthtoken=
SECRET_ENROLL_ENCRYPTION_TOKEN = "enroll_encryption_token" # IDP enrollencryptiontoken=
SECRET_UNINSTALL_PASSWORD      = "uninstall_password"      # protected uninstall

# ── Paths ─────────────────────────────────────────────────────────────────────

_KEY_DIR  = Path.home() / ".nsclient_test_base"
_KEY_FILE = _KEY_DIR / ".secret_key"
_STORE_FILE = Path(__file__).parent / "data" / "secrets.json"


# ── Key management ─────────────────────────────────────────────────────────────

def key_path() -> Path:
    """Return the path to the local key file (may not exist yet)."""
    return _KEY_FILE


def init_key(force: bool = False) -> Path:
    """
    Generate and save the Fernet key if it does not exist yet.

    Args:
        force: If True, overwrite an existing key (WARNING: existing secrets become unreadable).

    Returns:
        Path to the key file.
    """
    from cryptography.fernet import Fernet

    if _KEY_FILE.exists() and not force:
        log.debug("Key file already exists: %s", _KEY_FILE)
        return _KEY_FILE

    if force and _KEY_FILE.exists():
        log.warning("Overwriting existing key — all stored secrets will become unreadable")

    _KEY_DIR.mkdir(parents=True, exist_ok=True)
    key = Fernet.generate_key()
    _KEY_FILE.write_bytes(key)

    # Restrict permissions on Unix (no-op on Windows but harmless)
    try:
        import stat
        _KEY_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0o600
    except Exception:
        pass

    log.info("Secret key created: %s", _KEY_FILE)
    return _KEY_FILE


def _load_fernet():
    """Load the Fernet instance from the key file.  Raises if key missing."""
    from cryptography.fernet import Fernet

    if not _KEY_FILE.exists():
        raise FileNotFoundError(
            f"Secret key not found: {_KEY_FILE}\n"
            "Run: python tool/manage_secrets.py init"
        )
    return Fernet(_KEY_FILE.read_bytes())


# ── Secrets store I/O ─────────────────────────────────────────────────────────

def _load_store() -> dict:
    """Read data/secrets.json.  Returns empty dict if file missing."""
    if not _STORE_FILE.exists():
        return {}
    try:
        return json.loads(_STORE_FILE.read_text(encoding="utf-8"))
    except Exception:
        log.exception("Failed to read secrets store: %s", _STORE_FILE)
        return {}


def _save_store(data: dict) -> None:
    """Write data/secrets.json, creating parent dir if needed."""
    _STORE_FILE.parent.mkdir(parents=True, exist_ok=True)
    _STORE_FILE.write_text(json.dumps(data, indent=4), encoding="utf-8")


# ── Public API ────────────────────────────────────────────────────────────────

def store_secret(name: str, plaintext: str) -> None:
    """
    Encrypt ``plaintext`` and save it under ``name`` in the secrets store.

    Auto-generates the key file on first call if it does not exist.

    Args:
        name: Logical name (e.g. SECRET_CONFLUENCE_API_TOKEN).
        plaintext: The sensitive value to encrypt.
    """
    if not _KEY_FILE.exists():
        init_key()

    fernet = _load_fernet()
    ciphertext = fernet.encrypt(plaintext.encode("utf-8")).decode("ascii")

    store = _load_store()
    store[name] = ciphertext
    store["_meta"] = {
        "key_path": str(_KEY_FILE),
        "updated": time.strftime("%Y-%m-%d"),
    }
    _save_store(store)
    log.info("Secret stored: %s", name)


def get_secret(name: str) -> Optional[str]:
    """
    Decrypt and return the secret value for ``name``.

    Returns:
        Plaintext string, or None if the name is not found or decryption fails.
    """
    store = _load_store()
    ciphertext = store.get(name)
    if ciphertext is None or name.startswith("_"):
        return None

    try:
        fernet = _load_fernet()
        return fernet.decrypt(ciphertext.encode("ascii")).decode("utf-8")
    except FileNotFoundError as exc:
        log.error("%s", exc)
        return None
    except Exception:
        log.exception("Failed to decrypt secret: %s", name)
        return None


def list_secrets() -> list[str]:
    """Return all stored secret names (metadata keys excluded)."""
    store = _load_store()
    return [k for k in store if not k.startswith("_")]


def delete_secret(name: str) -> bool:
    """
    Remove a secret from the store.

    Returns:
        True if the secret existed and was removed, False if not found.
    """
    store = _load_store()
    if name not in store:
        log.warning("Secret not found: %s", name)
        return False
    del store[name]
    _save_store(store)
    log.info("Secret deleted: %s", name)
    return True


def secrets_configured() -> bool:
    """Return True if the key file and at least one secret exist."""
    return _KEY_FILE.exists() and bool(list_secrets())
